export const GETCONVERSATION = 'GETCONVERSATION';
export const UPDATECONVERSATION = 'UPDATECONVERSATION'
export const CONVERSATIONID = 'CONVERSATIONID'
export const RECIVERUSERID = 'RECIVERUSERID'
export const UPDATEMSG = 'UPDATEMSG'
export const MESSAGES = 'MESSAGES'


